// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"swl74d38zh","name":"dev-formyfertilityapi","description":"","endpoint":"https://swl74d38zh.execute-api.us-east-2.amazonaws.com/dev","region":"us-east-2","paths":["/formyfertility","/formyfertility/{id}"]}],
    'aws_cognito_identity_pool_id': 'us-east-2:4a7703c0-3713-4a9f-930d-cd5f7395f0e2',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'formyfertility-hosting-mobilehub-585886142',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2hdae6n2kmcnf.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'd82c9265cb84499989b76aecaf459f1a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '14cf1c8b-829e-4a68-906c-6d1b904c9ab0',
    'aws_project_name': 'ForMyFertility-2018-11-12-10-01-27',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'formyfertility-mobilehub-585886142',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_4IAy8d0hN',
    'aws_user_pools_web_client_id': '74pvh2f5vikpav6qna31o5int4',
}

export default awsmobile;
