// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:ce1a2366-ae19-4e95-a1b6-8fed791d21d6',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'fmf-hosting-mobilehub-2032962834',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1mh99nc9we5vq.cloudfront.net',
    'aws_mobile_analytics_app_id': '342bbc0998ea4dcf99aaca95989ec2fd',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '57944c4f-5803-43dc-ae75-7f753dddd8d0',
    'aws_project_name': 'fmf-2018-09-18-16-46-18',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'fmf-mobilehub-2032962834',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_Z0rr1fuWp',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3n5h1sihq9vf9894gg9ktgkhfp',
}

export default awsmobile;
