export default {
    abnormalities: "none",
    age: 2003,
    alcohol: "never",
    cigarettes: "never",
    enhancers: "none",
    exercise: "<1m",
    exercisetype: "other",
    frequency: "<1m",
    height: "5 feet 10 inches",
    jobactivity: "moderately",
    jobexposure: "none",
    lube: "no",
    marijuana: "never",
    medconditions: "none",
    gender: "male",
    pregnant: "no",
    sauna: "<1m",
    sleep: "<4",
    soy: "never",
    stressed: "never",
    superfoods: "none",
    drinks: "never",
    trying: "not",
    tv: "<1",
    veg: "never",
    weight: 165,
    questionNum: 1,
    questionTot: 26
};