// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:35df4417-8cd6-4c6e-95e8-e083544cb2d6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Q5dLU6CjP",
    "aws_user_pools_web_client_id": "5nftctqkqdlq72ljvot3nh9b4i",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "femalefertility-prod",
            "region": "us-east-2"
        },
        {
            "tableName": "malefertility-prod",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://7kkf7ryj4zby3pscqc7o6obtbi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "oddsapi",
            "endpoint": "https://q8458qpx8e.execute-api.us-east-2.amazonaws.com/prod",
            "region": "us-east-2"
        }
    ],
    "aws_mobile_analytics_app_id": "b4a40ae3d2d74b4e9d5b31f71b024d2e",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
