// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:60d95abf-96c3-4e1b-9273-f29eb9c7d9bd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vNe8wthNm",
    "aws_user_pools_web_client_id": "5srrjk4ddrup4i5vc9v39ilb67",
    "oauth": {},
    "aws_mobile_analytics_app_id": "d929a53337e342df9117e0e7c154e289",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "femalefertility-test",
            "region": "us-east-2"
        },
        {
            "tableName": "malefertility-test",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://spuipckza5arpnbplcf3ifmqpe.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "oddsapi",
            "endpoint": "https://xwmjubu5a6.execute-api.us-east-2.amazonaws.com/test",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
