// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "femalefertility-dev",
            "region": "us-east-2"
        },
        {
            "tableName": "malefertility-dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:e8c50823-93c0-4d96-bae5-8565036fdd40",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_raiO2Ngz7",
    "aws_user_pools_web_client_id": "ab8oh0v1mue8su2cs7quujb8f",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "oddsapi",
            "endpoint": "https://6ziwimmaa2.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://z7rrptdw2rhgharw63uibz4mnm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "0d8a8dc5df6e4065820a7f247431aec9",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
