// eslint-disable
// this is an auto generated file. This will be overwritten

<<<<<<< HEAD
export const createFemalefertility = `mutation CreateFemalefertility($input: CreateFemalefertilityInput!) {
  createFemalefertility(input: $input) {
    age
    amountChildren
    amountYearsChildlessSex
    amountperfecthealth
    currentIVF
    donoreggs
    donorembryos
    donorsperm
    eggs
    embryos
    embryosfinalcycle
    embryostransfered
    frozenembryos
    gender
    gestationalcarrier
    gynecologicalCauses
    hadEctopicPregnancy
    hadPregnancy
    hormone
    icsi
    id
    ivfconceived
    ivfcycles
    liveBirth
    miscarriages
    morethanoneivfconceived
    partner
    singletonmulitbirth
    username
    whichGynecologicalCauses
    whichPartnerIssue
    yearChildlessSex
  }
}
`;
export const createMalefertility = `mutation CreateMalefertility($input: CreateMalefertilityInput!) {
  createMalefertility(input: $input) {
    abnormalities
    age
    alcohol
    cigarettes
    drinks
    enhancers
    exercise
    exercisetype
    frequency
    gender
    height
    id
    jobactivity
    jobexposure
    lube
    marijuana
    medconditions
    pregnant
    sauna
    sleep
    soy
    stressed
    superfoods
    trying
    tv
    username
    veg
    weight
  }
}
`;
export const deleteFemalefertility = `mutation DeleteFemalefertility($input: DeleteFemalefertilityInput!) {
  deleteFemalefertility(input: $input) {
    age
    amountChildren
    amountYearsChildlessSex
    amountperfecthealth
    currentIVF
    donoreggs
    donorembryos
    donorsperm
    eggs
    embryos
    embryosfinalcycle
    embryostransfered
    frozenembryos
    gender
    gestationalcarrier
    gynecologicalCauses
    hadEctopicPregnancy
    hadPregnancy
    hormone
    icsi
    id
    ivfconceived
    ivfcycles
    liveBirth
    miscarriages
    morethanoneivfconceived
    partner
    singletonmulitbirth
    username
    whichGynecologicalCauses
    whichPartnerIssue
    yearChildlessSex
  }
}
`;
export const deleteMalefertility = `mutation DeleteMalefertility($input: DeleteMalefertilityInput!) {
  deleteMalefertility(input: $input) {
    abnormalities
    age
    alcohol
    cigarettes
    drinks
    enhancers
    exercise
    exercisetype
    frequency
    gender
    height
    id
    jobactivity
    jobexposure
    lube
    marijuana
    medconditions
    pregnant
    sauna
    sleep
    soy
    stressed
    superfoods
    trying
    tv
    username
    veg
    weight
  }
}
`;
export const updateFemalefertility = `mutation UpdateFemalefertility($input: UpdateFemalefertilityInput!) {
  updateFemalefertility(input: $input) {
    age
    amountChildren
    amountYearsChildlessSex
    amountperfecthealth
    currentIVF
    donoreggs
    donorembryos
    donorsperm
    eggs
    embryos
    embryosfinalcycle
    embryostransfered
    frozenembryos
    gender
    gestationalcarrier
    gynecologicalCauses
    hadEctopicPregnancy
    hadPregnancy
    hormone
    icsi
    id
    ivfconceived
    ivfcycles
    liveBirth
    miscarriages
    morethanoneivfconceived
    partner
    singletonmulitbirth
    username
    whichGynecologicalCauses
    whichPartnerIssue
    yearChildlessSex
  }
}
`;
export const updateMalefertility = `mutation UpdateMalefertility($input: UpdateMalefertilityInput!) {
  updateMalefertility(input: $input) {
    abnormalities
    age
    alcohol
    cigarettes
    drinks
    enhancers
    exercise
    exercisetype
    frequency
    gender
    height
    id
    jobactivity
    jobexposure
    lube
    marijuana
    medconditions
    pregnant
    sauna
    sleep
    soy
    stressed
    superfoods
    trying
    tv
    username
    veg
    weight
=======
export const createQuestions = `mutation CreateQuestions($input: CreateQuestionsInput!) {
  createQuestions(input: $input) {
    id
    username
    gender
    age
    yearChildlessSex
    amountYearsChildlessSex
    currentIVF
    hadPregnancy
    hadEctopicPregnancy
    liveBirth
    miscarriages
    partner
    whichPartnerIssue
    amountChildren
    amountperfecthealth
    donorsperm
    donoreggs
    donorembryos
    eggs
    embryos
    embryostransfered
    embryosfinalcycle
    frozenembryos
    gynecologicalCauses
    gestationalcarrier
    hormone
    icsi
    ivfcycles
    ivfconceived
    morethanoneivfconceived
    singletonmulitbirth
    whichGynecologicalCauses
  }
}
`;
export const updateQuestions = `mutation UpdateQuestions($input: UpdateQuestionsInput!) {
  updateQuestions(input: $input) {
    id
    username
    gender
    age
    yearChildlessSex
    amountYearsChildlessSex
    currentIVF
    hadPregnancy
    hadEctopicPregnancy
    liveBirth
    miscarriages
    partner
    whichPartnerIssue
    amountChildren
    amountperfecthealth
    donorsperm
    donoreggs
    donorembryos
    eggs
    embryos
    embryostransfered
    embryosfinalcycle
    frozenembryos
    gynecologicalCauses
    gestationalcarrier
    hormone
    icsi
    ivfcycles
    ivfconceived
    morethanoneivfconceived
    singletonmulitbirth
    whichGynecologicalCauses
  }
}
`;
export const deleteQuestions = `mutation DeleteQuestions($input: DeleteQuestionsInput!) {
  deleteQuestions(input: $input) {
    id
    username
    gender
    age
    yearChildlessSex
    amountYearsChildlessSex
    currentIVF
    hadPregnancy
    hadEctopicPregnancy
    liveBirth
    miscarriages
    partner
    whichPartnerIssue
    amountChildren
    amountperfecthealth
    donorsperm
    donoreggs
    donorembryos
    eggs
    embryos
    embryostransfered
    embryosfinalcycle
    frozenembryos
    gynecologicalCauses
    gestationalcarrier
    hormone
    icsi
    ivfcycles
    ivfconceived
    morethanoneivfconceived
    singletonmulitbirth
    whichGynecologicalCauses
>>>>>>> 45b5b9051805682dbd22fed3446ecb528421660d
  }
}
`;
